/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
static yyconst short int yy_acclist[211] =
    {   0,
       57,   56,   56,   39,   56,   46,   56,   41,   56,   42,
       56,   30,   56,   28,   56,   43,   56,   29,   56,   56,
       31,   56,   51,   56,   45,   56,   44,   56,   34,   56,
       32,   56,   35,   56,   54,   56,   54,   56,   54,   56,
       54,   56,   54,   56,   54,   56,   54,   56,   54,   56,
       54,   56,   54,   56,   54,   56,   54,   56,   54,   56,
       54,   56,   54,   56,   47,   55,   40,   52,   33,   51,
       38,   36,   37,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   13,   54,   21,   54,
       11,   54,   54,   54,   54,   54,   25,   54,   23,   54,

       54,   54,   54,   54,   54,   54,   54,   48,   55,   22,
       54,   54,   54,   54,   54,   54,   10,   54,   54,   54,
       20,   54,   54,   54,   54,   54,   24,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   53,   54,   54,   54,
       54,   16,   54,   54,   54,   54,   54,   54,   54,   18,
       54,   19,   54,   54,   54,   54,   54,   14,   54,   49,
       54,   54,    6,   54,    9,   54,   54,   54,   15,   54,
       50,   54,    3,   54,   54,   54,   54,   54,   26,   54,
       54,   54,   17,   54,   54,   54,   54,   54,   27,   54,
       54,   12,   54,    5,   54,    2,   54,   54,   54,    1,

       54,   54,   54,    8,   54,   54,    4,   54,    7,   54
    } ;

static yyconst short int yy_accept[162] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    8,   10,   12,
       14,   16,   18,   20,   21,   23,   25,   27,   29,   31,
       33,   35,   37,   39,   41,   43,   45,   47,   49,   51,
       53,   55,   57,   59,   61,   63,   65,   65,   66,   66,
       67,   68,   69,   70,   70,   71,   72,   73,   74,   75,
       75,   76,   77,   78,   79,   80,   81,   82,   83,   84,
       85,   86,   87,   89,   91,   93,   94,   95,   96,   97,
       99,  101,  102,  103,  104,  105,  106,  107,  108,  109,
      110,  110,  112,  113,  114,  115,  116,  117,  119,  120,
      121,  123,  124,  125,  126,  127,  129,  130,  131,  132,

      133,  134,  135,  136,  137,  137,  138,  139,  140,  141,
      142,  144,  145,  146,  147,  148,  149,  150,  152,  154,
      155,  156,  157,  158,  160,  162,  163,  165,  167,  168,
      169,  171,  173,  175,  176,  177,  178,  179,  181,  182,
      183,  185,  186,  187,  188,  189,  191,  192,  194,  196,
      198,  199,  200,  202,  203,  204,  206,  207,  209,  211,
      211
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   30,   32,   33,   34,
       30,   35,   36,   37,   38,   30,   39,   30,   40,   30,
        1,    1,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   30,   31,   30,   32,
       33,   34,   30,   35,   36,   37,   38,   30,   39,   30,
       40,   30,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[166] =
    {   0,
        0,    0,  161,  460,  145,  460,    0,  460,  460,  460,
      460,  460,  120,   29,  105,   30,  102,  460,   97,  460,
       93,   31,   32,   33,   34,   36,   50,   58,   60,   59,
       75,   82,   84,   62,   86,   98,  105,  100,   86,    0,
      460,   35,  460,   73,   63,  460,  460,  460,   66,   49,
       93,  105,  102,  113,  110,  114,  118,  122,  125,  127,
      130,  135,  137,  138,  139,  148,  149,  150,  152,  157,
      159,  164,  171,  172,  175,  174,  176,  184,  460,    0,
      191,  187,  197,  192,  202,  205,  206,  209,  210,  218,
      214,  222,  223,  227,  230,  235,  237,  238,  239,  242,

      249,  251,  256,  253,   48,   45,  265,  268,  272,  273,
      275,  276,  284,  287,  292,  294,  296,  297,  299,  306,
      314,  316,  318,  321,  323,  328,  326,  335,  338,  340,
      342,  347,  350,  351,  352,  354,  355,  364,  367,  369,
      371,  372,  374,  381,  383,  386,  388,  393,  395,  396,
      403,  405,  407,  410,  415,  418,  419,  420,  422,  460,
      450,  453,   55,  456,   52
    } ;

static yyconst short int yy_def[166] =
    {   0,
      160,    1,  160,  160,  161,  160,  162,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  161,  160,  160,  164,
      160,  160,  160,  160,  160,  160,  160,  160,  165,  165,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  160,  164,
      160,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,

      163,  163,  163,  163,  160,  160,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,    0,
      160,  160,  160,  160,  160
    } ;

static yyconst short int yy_nxt[501] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,    4,
       22,   23,   24,   25,   26,   27,   25,   25,   28,   25,
       29,   30,   31,   32,   33,   34,   35,   25,   36,   25,
       41,   44,   42,   45,   49,   49,   49,   49,   42,   49,
       50,   50,   50,   50,   49,   50,   54,   51,  106,   81,
       56,  106,   52,   49,   55,   53,   57,   58,  160,   50,
       59,   49,   49,   49,   44,   49,   45,   50,   50,   50,
       60,   50,   61,   63,   66,   50,   42,   62,   49,   64,
       79,   68,   67,   65,   50,   49,   69,   49,   75,   49,

       70,   50,   37,   50,   73,   50,   49,   38,   74,   71,
       48,   49,   50,   76,   47,   49,   72,   50,   49,   46,
       77,   50,   43,   49,   50,   78,   49,   49,   82,   50,
       40,   49,   50,   50,   86,   49,   83,   50,   49,   84,
       49,   50,   85,   49,   50,   88,   50,   38,   49,   50,
       49,   49,   49,   87,   50,   89,   50,   50,   50,   90,
      160,   49,   49,   49,   91,   49,   92,   50,   50,   50,
       49,   50,   49,  160,   93,  160,   50,   49,   50,   94,
      160,   95,   97,   50,   49,   49,   96,   49,   49,   49,
       50,   50,  160,   50,   50,   50,   98,   49,  102,  105,

       49,  105,   99,   50,  106,   49,   50,  160,  100,  101,
       49,   50,  104,  103,  160,   49,   50,  107,   49,   49,
      108,   50,   49,   49,   50,   50,  160,   49,   50,   50,
      111,   49,  109,   50,  112,   49,   49,   50,  114,  110,
       49,   50,   50,   49,  115,  113,   50,  116,   49,   50,
       49,   49,   49,  117,   50,   49,   50,   50,   50,  160,
      120,   50,   49,  118,   49,  121,   49,  119,   50,   49,
       50,  160,   50,  160,  160,   50,  160,  123,   49,  122,
      125,   49,  124,  126,   50,   49,   49,   50,   49,   49,
      160,   50,   50,  130,   50,   50,  129,   49,  160,  128,

       49,  131,  160,   50,  127,   49,   50,   49,  132,   49,
       49,   50,   49,   50,  160,   50,   50,  160,   50,   49,
      135,  160,  160,  133,  160,   50,  160,   49,  134,   49,
      137,   49,  136,   50,   49,   50,   49,   50,  138,   49,
       50,   49,   50,  160,  160,   50,  160,   50,   49,  140,
      139,   49,  141,   49,   50,   49,  160,   50,  142,   50,
       49,   50,  143,   49,   49,   49,   50,   49,   49,   50,
       50,   50,  160,   50,   50,  160,  145,   49,  147,  144,
       49,  146,   49,   50,   49,   49,   50,   49,   50,  160,
       50,   50,  160,   50,   49,  149,   49,  160,  148,   49,

       50,   49,   50,  150,  160,   50,   49,   50,   49,   49,
      151,  160,   50,  152,   50,   50,   49,  153,   49,  160,
       49,  160,   50,   49,   50,  154,   50,  155,   49,   50,
      160,   49,   49,   49,   50,   49,  156,   50,   50,   50,
      160,   50,  160,  159,  157,  160,  160,  160,  160,  158,
       37,  160,   37,   39,  160,   39,   80,  160,   80,    3,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160

    } ;

static yyconst short int yy_chk[501] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       14,   16,   14,   16,   22,   23,   24,   25,   42,   26,
       22,   23,   24,   25,  165,   26,   23,  163,  106,   42,
       24,  105,   22,   27,   23,   22,   26,   26,   50,   27,
       27,   28,   30,   29,   45,   34,   45,   28,   30,   29,
       27,   34,   27,   28,   29,   49,   44,   27,   31,   28,
       39,   30,   29,   28,   31,   32,   30,   33,   34,   35,

       31,   32,   38,   33,   33,   35,   51,   37,   33,   31,
       21,   36,   51,   35,   19,   53,   32,   36,   52,   17,
       35,   53,   15,   55,   52,   36,   54,   56,   52,   55,
       13,   57,   54,   56,   56,   58,   53,   57,   59,   54,
       60,   58,   55,   61,   59,   58,   60,    5,   62,   61,
       63,   64,   65,   57,   62,   59,   63,   64,   65,   60,
        3,   66,   67,   68,   61,   69,   62,   66,   67,   68,
       70,   69,   71,    0,   64,    0,   70,   72,   71,   66,
        0,   67,   69,   72,   73,   74,   68,   76,   75,   77,
       73,   74,    0,   76,   75,   77,   72,   78,   76,   81,

       82,   81,   73,   78,   81,   84,   82,    0,   74,   75,
       83,   84,   78,   77,    0,   85,   83,   83,   86,   87,
       84,   85,   88,   89,   86,   87,    0,   91,   88,   89,
       87,   90,   85,   91,   87,   92,   93,   90,   90,   86,
       94,   92,   93,   95,   92,   89,   94,   93,   96,   95,
       97,   98,   99,   94,   96,  100,   97,   98,   99,    0,
       98,  100,  101,   95,  102,   99,  104,   97,  101,  103,
      102,    0,  104,    0,    0,  103,    0,  101,  107,  100,
      103,  108,  102,  104,  107,  109,  110,  108,  111,  112,
        0,  109,  110,  110,  111,  112,  109,  113,    0,  108,

      114,  112,    0,  113,  107,  115,  114,  116,  113,  117,
      118,  115,  119,  116,    0,  117,  118,    0,  119,  120,
      116,    0,    0,  114,    0,  120,    0,  121,  115,  122,
      120,  123,  117,  121,  124,  122,  125,  123,  121,  127,
      124,  126,  125,    0,    0,  127,    0,  126,  128,  123,
      122,  129,  126,  130,  128,  131,    0,  129,  129,  130,
      132,  131,  130,  133,  134,  135,  132,  136,  137,  133,
      134,  135,    0,  136,  137,    0,  135,  138,  137,  134,
      139,  136,  140,  138,  141,  142,  139,  143,  140,    0,
      141,  142,    0,  143,  144,  140,  145,    0,  139,  146,

      144,  147,  145,  142,    0,  146,  148,  147,  149,  150,
      143,    0,  148,  144,  149,  150,  151,  145,  152,    0,
      153,    0,  151,  154,  152,  147,  153,  151,  155,  154,
        0,  156,  157,  158,  155,  159,  152,  156,  157,  158,
        0,  159,    0,  157,  154,    0,    0,    0,    0,  155,
      161,    0,  161,  162,    0,  162,  164,    0,  164,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "ada.flex"
#define INITIAL 0
#line 2 "ada.flex"
    #include "tree_nodes.h"
    #include "ada_bison_tab.h"
    #include <stdlib.h>
    #include <stdio.h>
    #include <string.h>
    #include <conio.h>
    #include <malloc.h>
    
    extern ProgramList *root;
    extern int yyparse(void);
#define YY_NEVER_INTERACTIVE 1
#line 572 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "ada.flex"



    int s = 0;
    char symbol[2];
    char buf[100000];
    memset(buf, '\0', 100000);


#line 729 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 161 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 460 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 37 "ada.flex"
{ yylval.vt = VT_INTEGER; return INTEGER;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "ada.flex"
{ yylval.vt = VT_BOOLEAN; return BOOLEAN;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "ada.flex"
{ yylval.vt = VT_FLOAT; return FLOAT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "ada.flex"
{ yylval.vt = VT_CHARACTER; return CHARACTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "ada.flex"
{ yylval.vt = VT_STRING; return STRING;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "ada.flex"
{return ARRAY;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "ada.flex"
{return PROCEDURE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "ada.flex"
{return FUNCTION;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "ada.flex"
{return BEGINs;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "ada.flex"
{return END;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "ada.flex"
{return IS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "ada.flex"
{return RETURN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "ada.flex"
{return IF;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "ada.flex"
{return THEN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "ada.flex"
{return ELSIF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "ada.flex"
{return ELSE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "ada.flex"
{return WHILE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "ada.flex"
{return LOOP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "ada.flex"
{return NIL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "ada.flex"
{return FOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "ada.flex"
{return IN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "ada.flex"
{return AND;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "ada.flex"
{return OR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "ada.flex"
{return NOT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "ada.flex"
{return OF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "ada.flex"
{return RANGE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "ada.flex"
{return LENGTH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "ada.flex"
{return '+';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "ada.flex"
{return '-';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "ada.flex"
{return '*';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "ada.flex"
{return '/';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "ada.flex"
{return '=';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "ada.flex"
{return NOT_EQUAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "ada.flex"
{return '<';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "ada.flex"
{return '>';}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "ada.flex"
{return LESSER_EQUAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "ada.flex"
{return GREATER_EQUAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "ada.flex"
{return ASSIGNMENT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "ada.flex"
{return '&';}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "ada.flex"
{return DOUBLE_DOT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "ada.flex"
{ return '('; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "ada.flex"
{ return ')'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "ada.flex"
{ return ','; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "ada.flex"
{ return ';'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "ada.flex"
{ return ':'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "ada.flex"
{ return '\''; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "ada.flex"
{   
                    yylval.string_const = (char *) malloc(strlen(yytext)-1);
					strncpy(yylval.string_const, yytext+1,strlen(yytext)-2);
                    
                    return CONST_STRING;
                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 97 "ada.flex"
{ yylval.char_const = *(yytext+1); return CONST_CHARACTER;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "ada.flex"
{ yylval.int_const = 1; return CONST_BOOL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "ada.flex"
{   yylval.int_const = 0; return CONST_BOOL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "ada.flex"
{ yylval.int_const = atoi(yytext); return CONST_INTEGER; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "ada.flex"
{ yylval.float_const = atof(yytext); return CONST_FLOAT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "ada.flex"
{ yylval.float_const = atof(yytext); return CONST_FLOAT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 105 "ada.flex"
{   yylval.id_const = (char *) malloc(strlen(yytext)+1);
                strcpy(yylval.id_const, yytext);
                
                return ID;
            }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "ada.flex"
{ }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "ada.flex"
ECHO;
	YY_BREAK
#line 1109 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 161 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 161 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 160);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 113 "ada.flex"


typedef struct TreeUnit TreeUnit;
struct TreeUnit
{
    char *label;
	char *edgeLabel;
	
    int num;
    int parentNum;
    
    TreeUnit *next;
};

typedef struct Tree Tree;
struct Tree
{
    TreeUnit * begin;
    TreeUnit * end;
};

FILE* fileOpen(int iter, const char* fname,const char* prefix, const char key);

void printTree(ProgramList *pr);
char *expr_type_str(EXPR_TYPE et);
char *stmt_type_str(STMT_TYPE et);
char *variable_type_str(VAR_TYPE et);


void print_node(int nodeNum, char *nodeName);
void print_edge(int numNode1, int numNode2, char* name);

TreeUnit *newTreeUnit(int parentNum, const char *label, const char *edgeLabel);
void addTreeUnit(Tree *tree, TreeUnit *element);

void programParse(Program *prog, Tree *tree, int parentNum);
void parseDeclarationStatementList(DeclarationStatementList *prog, Tree *tree, int parentNum);
void parseDeclarationStatement(DeclarationStatement *prog, Tree *tree, int parentNum);
void parseVariableDeclarationList(VariableDeclarationList *prog, Tree *tree, int parentNum);
void parseVariableDeclaration(VariableDeclaration *prog, Tree *tree, int parentNum);
void parseRange(Range *prog, Tree *tree, int parentNum);
void parseExpression(Expression *prog, Tree *tree, int parentNum);
void parseExpressionList(ExpressionList *prog, Tree *tree, int parentNum);
void parseVariableList(VariableList *prog, Tree *tree, int parentNum);
void parseStatementList(StatementList *prog, Tree *tree, int parentNum);
void parseStatement(Statement *prog, Tree *tree, int parentNum);
void parseWhileStatement(WhileStatement *whileStmt, Tree *tree, int parentNum);
void parseForStatement( ForStatement *prog, Tree *tree, int parentNum);
void parseIfStatement(IfStatement *prog, Tree *tree, int parentNum);
void parseElse(ElseStatement *prog, Tree *tree, int parentNum);
void parseElseIfStatementList(ElseIfStatementList *prog, Tree *tree, int parentNum);

void main()
{
    int iterator = 4;
    
    const char* infname = "in\\test";
    const char* outfname = "out\\output";
    
    if( yyin = fileOpen(iterator, infname, ".adb", 'r') )
    {
		yyparse();
		fclose (yyin);
		
		fileOpen(iterator, outfname, ".txt", 'w');
		printTree(root);
		fclose (stdout);
    }
}

FILE* fileOpen(int iter, const char* fname,const char* prefix, const char key)
{
    char outname[51];
    char fnum[7];
    
    strcpy(outname, fname);
    itoa(iter, fnum, 10);
    strcat(outname, fnum);
    strcat(outname, prefix);
    
    switch(key)
    {
        case 'r':
            return fopen(outname, "r");
        break;
    
        case 'w':
            return freopen(outname, "w", stdout);
        break;
    }
}

TreeUnit *newTreeUnit(int parentNum, const char *label, const char *edgeLabel)
{
    if(label!=NULL && edgeLabel!=NULL && parentNum>=0)
    {
        TreeUnit *unit = (TreeUnit *)malloc(sizeof(TreeUnit));
        
        unit->label = (char *)malloc( sizeof(char)*(strlen(label)+1) );
        strcpy(unit->label,label);
		
		unit->edgeLabel = (char *)malloc( sizeof(char)*(strlen(edgeLabel)+1) );
        strcpy(unit->edgeLabel,edgeLabel);
        
        unit->parentNum = parentNum;
		
		unit->next = NULL;
        
        return unit;
    }
    
    return NULL;
}

void addTreeUnit(Tree *tree, TreeUnit *element)
{
    if(tree!=NULL && element!=NULL )
    {
        if(tree->begin==NULL)
        {
            tree->begin = element;
            tree->end = element;
            element->num = 1;
        }
        else
        {
            tree->end->next = element;
            element->num = tree->end->num+1;
            tree->end = element;
        }
    }
}

//Tree print section


char *expr_type_str(EXPR_TYPE et)
{
    if(et==ET_INTEGER) return "ET_INTEGER";
    if(et==ET_FLOAT) return "ET_FLOAT";
    if(et==ET_STRING) return "ET_STRING";
    if(et==ET_CHARACTER) return "ET_CHARACTER";
    if(et==ET_ID) return "ET_ID";
    if(et==ET_ARRAY_OR_FUNC) return "ET_ARRAY_OR_FUNC";
    if(et==ET_BOOL) return "ET_BOOL";
    if(et==ET_EQUAL) return "=";
    if(et==ET_NOT_EQUAL) return "/=";
    if(et==ET_LESSER) return "<";
    if(et==ET_GREATER) return ">";
    if(et==ET_LESSER_EQUAL) return "<=";
    if(et==ET_GREATER_EQUAL) return ">=";
    if(et==ET_PLUS) return "+";
    if(et==ET_MINUS) return "-";
    if(et==ET_CONCAT) return "&";
    if(et==ET_MULT) return "*";
    if(et==ET_DIV) return "/";
    if(et==ET_LOGIC_OR) return "OR";
    if(et==ET_LOGIC_AND) return "AND";
    if(et==ET_ASSIGN) return ":=";
    if(et==ET_NOT) return "NOT";
    if(et==ET_RANGE_ARR_ATTR) return "ET_RANGE_ARR_ATTR";
    if(et==ET_LENGTH_ARR_ATTR) return "ET_LENGTH_ARR_ATTR";
    return "";
}

char *stmt_type_str(STMT_TYPE et)
{
    if(et==ST_EXPRESSION) return "ST_EXPRESSION";
    if(et==ST_RETURN) return "ST_RETURN";
    if(et==ST_NULL) return "ST_NULL";
    if(et==ST_WHILE) return "ST_WHILE";
    if(et==ST_FOR) return "ST_FOR";
    if(et==ST_IF) return "ST_IF";
    if(et==ST_ASSIGN) return ":=";
    return "";
}

char *variable_type_str(VAR_TYPE et)
{
    if(et==VT_INTEGER) return "INTEGER";
    if(et==VT_FLOAT) return "FLOAT";
    if(et==VT_BOOLEAN) return "BOOLEAN";
    if(et==VT_STRING) return "STRING";
    if(et==VT_CHARACTER) return "CHARACTER";
    if(et==VT_ARRAY) return "ARRAY";
    if(et==VT_VOID) return "VOID";
    return "";
}


void print_node(int nodeNum, char *nodeName)
{
    printf("%d  [label=\"%s\"];\n",nodeNum,nodeName);
}

void print_edge(int numNode1, int numNode2, char* name)
{
    printf("%d->%d[label=\"%s\"];\n",numNode1,numNode2,name);
}

void printTree(ProgramList *pr)
{
    if(pr!=NULL)
    {
        Tree *tree = (Tree *)malloc(sizeof(Tree));
        tree->begin = NULL;
        tree->end = NULL;
		
        programParse(pr->end, tree, 0);
        
		printf("digraph Program {\n");
		
			TreeUnit *i_units = tree->begin;
			while(i_units!=NULL)
			{
				print_node(i_units->num,i_units->label);
				i_units = i_units->next;
			}
			printf("\n");
			TreeUnit *i_parent = tree->begin;
			while(i_parent!=NULL)
			{
				TreeUnit *i_child = tree->begin;
				while(i_child!=NULL)
				{
					if(i_parent->num==i_child->parentNum)
					{
						print_edge(i_parent->num, i_child->num,i_child->edgeLabel);
					}
					
					i_child = i_child->next;
				}
				i_parent = i_parent->next;
			}
			
		printf("\n}");
    }
}

void programParse(Program *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
    {
        //main title
        addTreeUnit(tree, newTreeUnit(parentNum,prog->id,"Function"));
		int currentIter = tree->end->num;
        
        //parts of program
        if(prog->declarationSection!=NULL)
        {
            parseDeclarationStatementList(prog->declarationSection,tree,currentIter);
        }
        
        if(prog->performSection!=NULL)
        {
            parseStatementList(prog->performSection,tree,currentIter);
        }
        
        if(prog->globalariables!=NULL)
        {
			parseVariableDeclarationList(prog->globalariables,tree,currentIter);
        }
        
        //type of function
        addTreeUnit(
			tree, 
			newTreeUnit(currentIter,variable_type_str(prog->returnType),
			"Return type"));
    }
}

void parseDeclarationStatementList(DeclarationStatementList *prog, Tree *tree, int parentNum)
{
	addTreeUnit(tree, newTreeUnit(parentNum,"DeclarationStatementList",""));
	int currentIter = tree->end->num;

    if(prog!=NULL)
    {
		DeclarationStatement *ds = prog->begin;
        for(; ds!=NULL; ds = ds->nextInList)
        {
            parseDeclarationStatement(ds,tree,currentIter);
        }
    }
}

void parseDeclarationStatement(DeclarationStatement *prog, Tree *tree, int parentNum)
{
	addTreeUnit(tree, newTreeUnit(parentNum,"DeclarationStatement",""));
	int currentIter = tree->end->num;

	if(prog!=NULL)
	{
		switch(prog->type)
		{
			case DT_FUNCTION:
				programParse(prog->stmt.prog, tree, currentIter);
			break;
			
			case DT_VARIABLE:
				parseVariableDeclaration(prog->stmt.varDecl, tree, currentIter);
			break;
		}
	}
}

void parseVariableDeclarationList(VariableDeclarationList *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"VariableDeclarationList",""));
		int currentIter = tree->end->num;
	
		VariableDeclaration *ds = prog->begin;
		for(; ds!=NULL; ds = ds->nextInList)
        {
			parseVariableDeclaration(ds, tree, currentIter);
        }
    }
}

void parseVariableDeclaration(VariableDeclaration *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"VariableDeclaration",""));
		int currentIter = tree->end->num;
        
		addTreeUnit(tree, newTreeUnit(currentIter,variable_type_str(prog->type),""));
		
        if(prog->isArray)
        {
			addTreeUnit(tree, newTreeUnit(currentIter,"Array",""));
			
            parseRange(prog->range, tree, currentIter);
        }
		
		if(prog->varList!=NULL)
		{
			parseVariableList(prog->varList, tree, currentIter);
		}
    }
}

void parseRange(Range *prog, Tree *tree, int parentNum)
{
    addTreeUnit(tree, newTreeUnit(parentNum,"Range",""));
	int currentIter = tree->end->num;
    
	if(prog!=NULL)
	{
		if(prog->id!=NULL)
		{
			addTreeUnit(tree, newTreeUnit(currentIter,prog->id,"iterator"));
		}
		
		if(prog->startIndex!=NULL)
		{
			parseExpression(prog->startIndex,tree,currentIter);
		}
		
		if(prog->lastIndex!=NULL)
		{
			parseExpression(prog->lastIndex,tree,currentIter);
		}
	}
}

void parseExpression(Expression *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
	{
		addTreeUnit(tree, newTreeUnit(parentNum,expr_type_str(prog->type),"Expression"));
		int currentIter = tree->end->num;
		
		char buf[51];
		switch(prog->type)
		{
			case ET_INTEGER :
			case ET_BOOL:
			
				itoa(prog->val.int_val,buf,10);
				
				addTreeUnit(tree, newTreeUnit(currentIter,buf,expr_type_str(prog->type)));
			break;
			
			case ET_FLOAT:
			
				sprintf(buf, "%f", prog->val.float_val);
				
				addTreeUnit(tree, newTreeUnit(currentIter,buf,"float"));
			break;
			
			case ET_STRING:
			case ET_ID:
			case ET_LENGTH_ARR_ATTR:
			
				addTreeUnit(tree, 
							newTreeUnit(currentIter,prog->val.string_val,expr_type_str(prog->type)));
			break;
			
			case ET_ARRAY_OR_FUNC:
				addTreeUnit(tree, newTreeUnit(currentIter,prog->val.string_val,expr_type_str(prog->type)));
				parseExpressionList(prog->exprList, tree, currentIter);
				
			break;
			
			case ET_CHARACTER:
				buf[0]=prog->val.char_val;buf[1]='\0';
				addTreeUnit(tree, newTreeUnit(currentIter,buf,"character"));
			break;
			
			default:
				
				if(prog->left!=NULL){
					parseExpression(prog->left, tree, currentIter);
				}
				
				if(prog->right!=NULL){
					parseExpression(prog->right, tree, currentIter);
				}
		}
		
		//if(prog->exprList!=NULL)
		//{
		//	parseExpressionList(prog->exprList, tree, currentIter);
		//}
	}
}

void parseExpressionList(ExpressionList *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"ExpressionList",""));
		int currentIter = tree->end->num;
		
		Expression *ds = prog->begin;
		for(; ds!=NULL; ds = ds->nextInList)
        {
            parseExpression(ds,tree,currentIter);
        }
    }
}

void parseVariableList(VariableList *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
	{
		addTreeUnit(tree, newTreeUnit(parentNum,"VariableList",""));
		int currentIter = tree->end->num;
		
		VariableList *ds = prog;
		for(; ds!=NULL; ds = ds->nextInList)
        {
			addTreeUnit(tree, newTreeUnit(currentIter,ds->id,"variable"));
        }
	}
}

void parseStatementList(StatementList *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"StatementList",""));
		int currentIter = tree->end->num;
		
		Statement *ds = prog->begin;
		for(; ds!=NULL; ds = ds->nextInList)
        {
            parseStatement(ds,tree,currentIter);
        }
    }   
}

void parseStatement(Statement *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
	{
		addTreeUnit(tree, newTreeUnit(parentNum,stmt_type_str(prog->type),"Statement"));
		int currentIter = tree->end->num;
	
		switch(prog->type)
		{
			case ST_EXPRESSION:
				parseExpression(prog->stmtVal.exprStmt,tree,currentIter);
			break;
			
			case ST_RETURN:
				parseExpression(prog->stmtVal.exprStmt,tree,currentIter);
			break;
			
			case ST_NULL:
				addTreeUnit(tree, newTreeUnit(currentIter,"NULL",""));
			break;
			
			case ST_WHILE:
				parseWhileStatement(prog->stmtVal.whileStmt,tree,currentIter);
			break;
			
			case ST_FOR:
				parseForStatement( prog->stmtVal.forStmt, tree, currentIter);
			break;
			
			case ST_IF:
				parseIfStatement(prog->stmtVal.ifStmt, tree, currentIter);
			break;
			
			case ST_ASSIGN:
				parseExpression(prog->stmtVal.assigStmt->left,tree,currentIter);
				parseExpression(prog->stmtVal.assigStmt->right,tree,currentIter);
			break;
		}
	}
}

void parseWhileStatement(WhileStatement *whileStmt, Tree *tree, int parentNum)
{
    if(whileStmt!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"WhileStatement",""));
		int currentIter = tree->end->num;
	
		parseExpression(whileStmt->condition,tree,currentIter);

        parseStatementList(whileStmt->whileBlock, tree, currentIter);
    }
}

void parseForStatement( ForStatement *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"ForStatement",""));
		int currentIter = tree->end->num;
		
		addTreeUnit(tree, newTreeUnit(currentIter,prog->iterID,"iterator"));
		parseStatementList(prog->stmtList, tree, currentIter);
		parseRange(prog->range, tree, currentIter);
    }
}

void parseIfStatement(IfStatement *prog, Tree *tree, int parentNum)
{
    if(prog!=NULL)
	{
		addTreeUnit(tree, newTreeUnit(parentNum,"IfStatement",""));
		int currentIter = tree->end->num;
	
		parseExpression(prog->condition,tree,currentIter);
		parseStatementList(prog->stmtList, tree, currentIter);
		parseElse(prog->elseStmt, tree, currentIter);
		parseElseIfStatementList(prog->elseIfStmtList, tree, currentIter);
	}
}

void parseElse(ElseStatement *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
	{
		addTreeUnit(tree, newTreeUnit(parentNum,"ElseStatement",""));
		int currentIter = tree->end->num;
		
		parseStatementList(prog->stmtList, tree, currentIter);
	}
}

void parseElseIfStatementList(ElseIfStatementList *prog, Tree *tree, int parentNum)
{
	if(prog!=NULL)
    {
		addTreeUnit(tree, newTreeUnit(parentNum,"ElseIfStatementList",""));
		int currentIter = tree->end->num;
		
		ElseIfStatement *ds = prog->begin;
		for(; ds!=NULL; ds = ds->nextInList)
        {
			parseExpression(ds->condition,tree,currentIter);
			parseStatementList(ds->stmtList, tree, currentIter);
        }
    }
}